on:
    workflow_call:
        inputs:
            image-name:
                required: true
                type: string
            image-args:
                required: false
                type: string
                default: ""
            image-tag:
                required: false
                type: string
                default: "latest"
            dockerfile-path:
                required: false
                type: string
                default: "."
            dockerfile-name:
                required: false
                type: string
                default: "Dockerfile"

jobs:
    build_image:
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Check docker version
              run: docker version
            - if: inputs.image-args != ''
              name: Build docker image with args
              run: docker build --build-arg ${{ inputs.image-args }} -t ${{ inputs.image-name }}:${{ inputs.image-tag }} -f ${{ inputs.dockerfile-path }}/${{ inputs.dockerfile-name }} .
            - if: inputs.image-args == ''
              name: Build docker image without args
              run: docker build -t ${{ inputs.image-name }}:${{ inputs.image-tag }} -f ${{ inputs.dockerfile-path }}/${{ inputs.dockerfile-name }} .
            - name: Show image details
              run: docker image ls
