on:
    workflow_call:
        inputs:
            go-version:
                required: true
                type: string

jobs:
    gosec:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: ${{ inputs.go-version }}
            - name: Install GoSec
              run: go install github.com/securego/gosec/v2/cmd/gosec@latest
            - name: Run GoSec
              run: gosec ./...

    go_vuln_check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: ${{ inputs.go-version }}
            - name: Install GoVulnCheck
              run: go install golang.org/x/vuln/cmd/govulncheck@latest
            - name: Run GoVulnCheck
              run: govulncheck ./...
